import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import Footer from './component/footer';
import Navbar from './component/header';
import LeftSidebar from './component/LeftSidebar';
import RightSidebar from './component/RightSidebar';
import AImessage from './AI-massage';

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable}  bg-primary dark:bg-dark text-white`}>
				{/* Navbar */}
				<Navbar />

				{/* Page Content */}

				<div className='flex min-h-screen relative pt-24 flex-col md:flex-row  mx-auto bg-blue-50 dark:bg-blue-950 text-blue-500 dark:text-blue-100 w-full'>
					{/* Left Sidebar */}
					<LeftSidebar />

					{/* Main Content */}
					<main className='flex-grow'>{children}</main>

					{/* Right Sidebar */}
					<RightSidebar />
				</div>
				<AImessage />
				{/* Footer */}
				<Footer />
			</body>
		</html>
	);
}
