import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

import Footer from './component/footer';
import Navbar from './component/header';
import LeftSidebar from './component/LeftSidebar';
import RightSidebar from './component/RightSidebar';
import AImessage from './AI-massage';

import { Inconsolata, Roboto } from 'next/font/google';

// If loading a variable font, you don't need to specify the font weight
const inter = Inconsolata({ subsets: ['latin'], weight: '700' });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`bg-gradient-to-r ${inter.className} from-third via-primary to-third dark:from-darksecoundry dark:via-black dark:to-darksecoundry  `}>
				<Navbar />
				<div className=' m-auto container '>
					<div className='flex min-h-screen relative pt-[83px] flex-col lg:flex-row  mx-auto  text-blue-500 dark:text-blue-100 w-full'>
						<LeftSidebar />

						<main className='flex-grow'>{children}</main>

						<RightSidebar />
					</div>
					<AImessage />

					<Footer />
				</div>
			</body>
		</html>
	);
}
